const PLAYER_CLASSES = {
  shooter: {
    id: "shooter",
    name: "Стрелок",
    description: "Базовый карась без специальных ролей, упор на ровную стрельбу.",
    spriteKey: null,
    maxHealth: 100,
    fireCooldown: 0.22,
    bulletSpeed: 460,
    bulletDamage: 1,
    bulletRadius: 5,
    doubleShotOffsets: [-11, 11],
    singleShotOffset: 2,
    riseAcceleration: -980,
    fallAcceleration: 720,
    maxRiseSpeed: -260,
    maxFallSpeed: 320,
    invulnerabilityDuration: 0.7,
    renderScaleX: 1.24,
    renderScaleY: 1.3,
    renderOffsetX: -0.62,
    renderOffsetY: -0.65,
  },
  engineer: {
    id: "engineer",
    name: "Инженер",
    description: "Базовый каркас для оружия, турелей и технических умений.",
    spriteKey: "engineerImage",
    maxHealth: 100,
    fireCooldown: 0.22,
    bulletSpeed: 460,
    bulletDamage: 1,
    bulletRadius: 5,
    doubleShotOffsets: [-11, 11],
    singleShotOffset: 2,
    riseAcceleration: -980,
    fallAcceleration: 720,
    maxRiseSpeed: -260,
    maxFallSpeed: 320,
    invulnerabilityDuration: 0.7,
    renderScaleX: 1.24,
    renderScaleY: 1.3,
    renderOffsetX: -0.62,
    renderOffsetY: -0.65,
  },
  medic: {
    id: "medic",
    name: "Медик",
    description: "Базовый каркас для лечения, поддержки и командных бонусов.",
    spriteKey: "medicImage",
    maxHealth: 100,
    fireCooldown: 0.22,
    bulletSpeed: 460,
    bulletDamage: 1,
    bulletRadius: 5,
    doubleShotOffsets: [-11, 11],
    singleShotOffset: 2,
    riseAcceleration: -980,
    fallAcceleration: 720,
    maxRiseSpeed: -260,
    maxFallSpeed: 320,
    invulnerabilityDuration: 0.7,
    renderScaleX: 1.24,
    renderScaleY: 1.3,
    renderOffsetX: -0.62,
    renderOffsetY: -0.65,
  },
};

const DEFAULT_PLAYER_CLASS_ID = "shooter";

function getPlayerClassConfig(classId) {
  return PLAYER_CLASSES[classId] || PLAYER_CLASSES[DEFAULT_PLAYER_CLASS_ID];
}

window.PlayerClasses = {
  all: PLAYER_CLASSES,
  defaultId: DEFAULT_PLAYER_CLASS_ID,
  getConfig: getPlayerClassConfig,
};
